app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, BooleanField, SelectField, ValidationError
from wtforms.validators import DataRequired, Length, Email, Regexp
from flask_pagedown.fields import PageDownField
from ..models import Role, User
from flaskckeditor import CKEditor


class EditProfileForm(Form):
    name = StringField('Real name', validators=[Length(min=0, max=64)])
    location = StringField('Location', validators=[Length(min=0, max=64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')


class EditProfileAdminForm(Form):
    email = StringField('Email', validators=[DataRequired(),
                                             Length(min=1, max=64),
                                             Email()])
    username = StringField('Username', validators=[DataRequired(),
                                                   Length(min=1, max=64),
                                                   Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0,
                                                          'Usernames must have only letters, '
                                                          'numbers, dots or underscores')])
    confirmed = BooleanField('Confirmed')
    role = SelectField('Role', coerce=int)
    name = StringField('Real name', validators=[Length(min=0, max=64)])
    location = StringField('Location', validators=[Length(min=0, max=64)])
    about_me = TextAreaField('About Me')
    submit = SubmitField('Submit')

    # used to transform the integer value of a role in a string order by Role.name
    def __init__(self, user, *args, **kwargs):
        super(EditProfileAdminForm, self).__init__(*args, **kwargs)
        self.role.choices = [(role.id, role.name)
                             for role in Role.query.order_by(Role.name).all()]
        self.user = user

    def validate_email(self, field):
        if field.data != self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registred.')

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already in use.')


class PostForm(Form):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=64)])
    body = PageDownField("What's on your mind?", validators=[DataRequired()])
    submit = SubmitField("Submit")


class CommentForm(Form):
    body = PageDownField('', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CKEditorForm(Form, CKEditor):
    title = StringField("Title", validators=[DataRequired(), Length(min=1, max=64)])
    body = PageDownField(validators=[DataRequired()])
    submit = SubmitField('Posten!')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
from ..models import Permission


# Macht die Klasse Permission global in jedem Template verfügbar
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from . import main
from .. import db
from flask import render_template, abort, flash, redirect, url_for, request
from ..models import User, Permission, Post
from flask_login import login_required, current_user, current_app
from .forms import CKEditorForm, EditProfileForm, EditProfileAdminForm, PostForm, CommentForm
from ..decorators import admin_required, permission_required
from ..models import Role, Comment


@main.route('/writeArticle', methods=['GET', 'POST'])
def write_article():
    form = CKEditorForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    return render_template('write_article.html', form=form)


@main.route('/ckupload', methods=['POST', 'OPTIONS'])
def ckupload():
    form = CKEditorForm()
    response = form.upload(endpoint=main)
    return response


@main.route('/', methods=['GET', 'POST'])
def index():
    form = PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
        post = Post(title=form.title.data,
                    body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('main.html', form=form, posts=posts, pagination=pagination)


@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    posts = user.posts.order_by(Post.timestamp.desc()).all()
    return render_template('user.html', user=user, posts=posts)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user)
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@main.route('/edit-profile/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user = User.query.get_or_404(id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email = form.email.data
        user.username = form.username.data
        user.confirmed = form.confirmed.data
        user.role = Role.query.get(form.role.data)
        user.name = form.name.data
        user.location = form.location.data
        user.about_me = form.about_me.data
        db.session.add(user)
        flash('The profile has been updated.')
        return redirect(url_for('.user', username=user.username))
    form.email.data = user.email
    form.username.data = user.username
    form.confirmed.data = user.confirmed
    form.role.data = user.role_id
    form.name.data = user.name
    form.location.data = user.location
    form.about_me.data = user.about_me
    return render_template('edit_profile.html', form=form, user=user)


@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        flash('Your comment has been published.')
        return redirect(url_for('.post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() -1) / current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('post.html', posts=[post], form=form,
                           comments=comments, pagination=pagination)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        flash('The post has been updated.')
        return redirect(url_for('.post', id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    return render_template('edit_post.html', form=form)


@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page = request.args.get('page', 1, type=int)
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('moderate.html', comments=comments,
                           pagination=pagination, page=page)


@main.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = False
    db.session.add(comment)
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))


@main.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment = Comment.query.get_or_404(id)
    comment.disabled = True
    db.session.add(comment)
    return redirect(url_for('.moderate', page=request.args.get('page', 1, type=int)))

app/templates/_comments.html
{% for comment in comments %}
<div class="panel panel-default">
  <div class="panel-body">
      <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {% if comment.disabled %}
        <p><i>This comment has been disabled by a moderator.</i></p>
      {% endif %}
      {% if moderate or not comment.disabled %}
        {% if comment.body_html %}
            {{ comment.body_html | safe }}
        {% else %}
            {{ comment.body }}
        {% endif %}
      {% endif %}
  </div>
  <div class="panel-footer">
      <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
      <div class="comment-author">Autor: <a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
      {% if moderate %}
        {% if comment.disabled %}
            <a class="btn btn-default btn-xs pull-right" href="{{ url_for('.moderate_enable', id=comment.id, page=page) }}">Enable</a>
        {% else %}
            <a class="btn btn-danger btn-xs pull-right" href="{{ url_for('.moderate_disable', id=comment.id, page=page) }}">Disable</a>
        {% endif %}
      {% endif %}
  </div>
</div>
{% endfor %}

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li {% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
        page = pagination.page - 1, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li {% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
        page = pagination.page + 1, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_posts.html
{% for post in posts %}
    <!-- Blog Post -->
    <h2>
        {% if current_user.is_authenticated %}
            {% if current_user == post.author or current_user.is_administrator %}
            <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {% endif %}
        {% endif %}
        <a href="{{ url_for('.post', id=post.id) }}">{{ post.title }}</a>
    </h2>
    <p class="lead">
        by <a href="{{ url_for('.user', username=post.author.username) }}">{{ post.author.username }}</a>
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on {{ moment(post.timestamp).fromNow() }}</p>
    <p><span class="glyphicon glyphicon-calendar"></span> Posted on {{ moment(post.timestamp).format('LLL') }}</p>
    <hr>
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">
    <hr>
        <p>{% if post.body_html %}
                {{ post.body_html | safe }}
            {% else %}
                {{ post.body }}
            {% endif %}
        </p>
        <a class="btn btn-primary" href="{{ url_for('.post', id=post.id) }}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
        {% if current_user.is_authenticated %}
            {% if current_user == post.author %}
            <a class="btn btn-primary" href="{{ url_for('.edit', id=post.id) }}">Edit <span class="glyphicon glyphicon-edit"></span></a>
            {% elif current_user.is_administrator %}
            <a class="btn btn-danger" href="{{ url_for('.edit', id=post.id) }}">Edit [Admin] <span class="glyphicon glyphicon-edit"></span></a>
            {% endif %}
        {% endif %}
        <a class="btn btn-primary" href="{{ url_for('.post', id=post.id) }}#comments">{{ post.comments.count() }} Comments</a>
</a>
    <hr>
{% endfor %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="david schenk">

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/blog-home.css') }}" rel="stylesheet">

    <!-- 404 CSS -->
    <link href="{{ url_for('static', filename='css/error.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    {% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">sauerbraten</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li>
                        <a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="#">About us</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.can(Permission.WRITE_ARTICLES) %}
                    <li><a href="{{ url_for('main.write_article') }}">Blog Post</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                    <li><a href="{{ url_for('main.moderate') }}">Moderate Comments</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- Avatar later -->
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                            <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% endblock %}

    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
            {% endfor %}
        {% endif %}
        {% endwith %}


    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <hr>
                <p>Copyright &copy; sauerbraten.de 2016</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>

    <!-- /.container -->
    </div>

    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>

    {% block scripts %}
        {{ moment.include_moment() }}
        {{ pagedown.include_pagedown() }}
    {% endblock %}

</body>

</html>

app/templates/blog-post.html
{% block blog-post %}
<h2>
    <a href="#">Blog Post Title</a>
</h2>
<p class="lead">
    by <a href="index.php">Start Bootstrap</a>
</p>
<p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
<hr>
<img class="img-responsive" src="http://placehold.it/900x300" alt="">
<hr>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore, veritatis, tempora, necessitatibus inventore nisi quam quia repellat ut tempore laborum possimus eum dicta id animi corrupti debitis ipsum officiis rerum.</p>
<a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
<hr>
{% endblock %}

app/templates/demo.html
{% extends 'base.html' %}

{% block content %}
<!-- Content -->
<div class="container">
    <div class='panel panel-default'>
        <div class='panel-heading'>
            <i class='icon-edit icon-large'></i>
            APP Demo
        </div>
        <div class='panel-body'>
            <form method="post">
                {{ form.hidden_tag() }}
                {{ form.title(class='form-control', placeholder='appDemo', type='text') }}
                {{ form.ckdemo(class='ckeditor') }}
                <script type="text/javascript">
                    CKEDITOR.replace("ckdemo", {
                        filebrowserUploadUrl: '/ckupload',
                        filebrowserImageUploadUrl: '/ckupload'
                    });
                </script>
                {{ form.submit(class="btn btn-default") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>Edit Post</h1>
    </div>
    <div>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div clas="row">
    <div class="page-header">
        <h1>Edit Your Profile</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block content %}

    <!-- Page Content -->
        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <h1 class="page-header">

                    Willkommen
                    {% if current_user.is_authenticated %}
                        {{ current_user.username|capitalize }}.
                    {% else %}
                        Fremder!<br>
                    <small>Melde dich an, um alle Features nutzen zu können!</small>
                    {% endif %}
                </h1>

                {% if current_user.can(Permission.WRITE_ARTICLES) %}
                {{ wtf.quick_form(form) }}
                {% endif %}

                <hr>

                {% include '_posts.html' %}

                {% if pagination %}
                <!-- Pager -->
                <div class="pagination">
                    {{ macros.pagination_widget(pagination, '.index') }}
                </div>
                {% endif %}

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->
{% endblock %}

app/templates/moderate.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}Comment Moderation{% endblock %}

{% block content %}
<div class="page-header">
    <h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.moderate') }}
</div>
{% endif %}
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Post{% endblock %}

{% block content %}
{% include '_posts.html' %}
<h4 id="comments">Comments</h4>
{% if current_user.can(Permission.COMMENT) %}
<div class="comment-form">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
<hr>
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.post', fragment='#comments', id=posts[0].id) }}
</div>
{% endif %}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="row">
    <div class="page-header">
        <h1>
            {{ user.username }}
        </h1>
    </div>
    <div class="col-md-4">
        {% if user.name or user.location %}
        <p>
            {% if user.name %}{{ user.name }}{% endif %}
            {% if user.location %}
                From <a href="http://maps.google.com/?q={{ user.location }}">
                {{ user.location }}
            </a>
            {% endif %}
        </p>
        {% endif %}
        {% if current_user.is_administrator %}
        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
            Member since {{ moment(user.member_since).format('L') }}.
            Last seen {{ moment(user.last_seen).fromNow() }}.
        </p>
        {% if user == current_user %}
        <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">
            Edit Profile
        </a>
        {% endif %}
        {% if current_user.is_administrator %}
        <a class="btn btn-danger"
            href="{{ url_for('.edit_profile_admin', id=user.id) }}">
            Edit Profile [Admin]
        </a>
        {% endif %}
    </div>
</div>
<hr>
<div class="row">
    <div class="container">
        <div class="col-md-8">
            <h3>Posts by {{ user.username }}</h3>
            <hr>
            {% include '_posts.html' %}

            {% if pagination %}
                <!-- Pager -->
                <div class="pagination">
                    {{ macros.pagination_widget(pagination, '.index') }}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/write_article.html
{% extends 'base.html' %}

{% block content %}
<!-- Content -->
<div class="row">
    <div class="page-header">
        <h1>
            Write an article!
        </h1>
    </div>
    <div class="col-md-10">
        <form method="post">
            {{ form.hidden_tag() }}
            {{ form.title(class='form-control', placeholder='title', type='text') }}
            {{ form.body(class='ckeditor') }}
            <script type="text/javascript">
                CKEDITOR.replace("body", {
                    filebrowserUploadUrl: '/ckupload',
                    filebrowserImageUploadUrl: '/ckupload'
                 });
            </script>
            {{ form.submit(class="btn btn-default") }}
        </form>
    </div>
</div>
{% endblock %}